export const enum userGitHubTypeAction{
    LOAD_USER_REPOS = '[LOAD_USER_REPOS] LOAD USER REPOS',
    LOAD_USER_REPOS_RESPONSE_SUCCESS = '[LOAD_USER_REPOS_RESPONSE_SUCCESS] LOAD USER REPOS RESPONSE SUCCESS',
    LOAD_USER_REPOS_RESPONSE_NOT_FOUND = '[LOAD_USER_REPOS_RESPONSE_NOT_FOUND] LOAD USER REPOS NOT FOUND',
}
